### ISSUE TITLE
Fails to run code initially at startup

### ISSUE THREAD

**Issue by emlyn** [llloret/sonic-pi-vscode-editor#2]
If I start the extension, and there is already a ruby tab open (from the previous run), and I hit alt+R without first clicking in the open tab, it doesn't play it but instead logs:
```
stdout: Studio - Pausing SuperCollider Audio Server

stderr: workspace_nine: warning: ... at EOL, should be parenthesized?
workspace_nine:1: warning: ... at EOL, should be parenthesized?

Starting run 7
Completed run 7
All runs completed
Pausing SuperCollider Audio Server
```
It looks like it is sending something other than the contents of the tab to Sonic Pi.
Probably it should either use the open tab, or at least refuse to run until the a compatible tab is focussed.

**Comment by llloret** [comment]
Thank you for reporting this, @emlyn  .

Ok, I know what the issue is. It is trying to run the log contents... :). I will fix it when I have a break from work later today.

Also, I will add the mac keybindings, I think I have found how to have different ones for the different platforms.

**Comment by llloret** [comment]
OK, I think this should be fixed with the latest master. @emlyn , can you give it a quick test?

Also, on Mac it should use the same keybinding as Sonic Pi, not alt-R.

**Comment by emlyn** [comment]
Thanks, that works well now :-)
