### ISSUE TITLE
update README.md. Sonic Pi must be open when running the code from VS Code using the extension

### ISSUE THREAD

**Issue by piscespieces** [llloret/sonic-pi-vscode-editor#9]
Sometimes one struggles with the most obvious things,

After cloning this repo, setting up my Sonic Pi Root Dir, and reading like 10 times the `README.md` I wasn't getting to work the extension. The issue was that I had to boot the actual Sonic Pi app to hear the code that I was running.

Of course once you get it working then the documentation (`README.md`) makes sense, but before that, even though the documentation is pretty clear and straight forward I was getting confused by little things. Maybe because I was overthinking it but in order to avoid these noob confusions I would say that the `README.md` might need an update.

**Comment by ethancrawford** [comment]
Thanks for the advice @piscespieces - sounds like a good idea 👍
